FROM python:3.8.10

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install torch torchvision tensorboard nvflare==2.0.16
RUN python3 -m pip install boto3 pandas protobuf==3.20

RUN apt-get update && apt-get install -y dos2unix
RUN apt-get install -y wget

RUN wget https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
RUN mkdir /root/data
RUN tar -C /root/data -xzvf cifar-10-python.tar.gz

WORKDIR /nvflare/
RUN git clone https://github.com/NVIDIA/NVFlare.git
COPY start_nvflare_components.sh start_nvflare_components.sh

RUN dos2unix ./start_nvflare_components.sh

RUN yes | poc -n 2

WORKDIR /nvflare/poc/admin/
COPY apps transfer/
COPY test.py ./

ENV PATH="${PATH}:/nvflare/poc/admin/startup"

WORKDIR /nvflare/

RUN chmod 777 ./start_nvflare_components.sh
CMD ["./start_nvflare_components.sh"]